### ISSUE TITLE
Asset Pipeline Support

### ISSUE THREAD

**Issue by dhedlund** [calagator/calagator#43]
I made some commits to enable the asset pipeline in calagator, see:
https://github.com/dhedlund/calagator/compare/asset_pipeline

I'm looking for feedback from the calagator maintainers as to the direction they would me to proceed before I submit a pull request.
#### Background

_TL;DR: themes_for_rails gem is dead and without working theme-level assets.  Forks exist but still have problems._

Calagator currently doesn't support the asset pipeline at all.  Transitioning to the asset pipeline is generally straightforward but the **themes_for_rails** gem doesn't properly support it, at least not in a typical production mode that takes advantage of precompling assets.

The commits I've made so far enable the asset pipeline for core calagator assets (anything under app/assets) but everything managed by themes_for_rails has still has to be written in pure css or javascript and copied to the public/ directory using the `rake themes:create_cache` command.

There are forks on GitHub that attempt to update the gem to precompile assets, but it looks like the main gem is dead; the last commit was 9 months ago and the one before that was over a year.  The owner has also not replied to any issues in a similar time frame.  The forks look like they get it about 85-90% of the way there, but they still have some problems and the code feels more hackish that it should be.  The most recent fork, incorporating the asset pipeline changes from other forks is: https://github.com/digitalmoksha/themes_for_rails/compare/lucasefe:master...master

I say 85-90% because there are a couple todo sections and I don't see a way to explicitly define a list of assets to compile at the theme level; I haven't tried it but I assume they're either assuming wildcard asset inclusion, i.e `config.assets.precompile += %w( *.js *.css )` or that you will name asset files very consistently across themes and never introduce a new externally-facing asset file within your theme (i.e. those that get included if a conditional in the view is triggered).  

Wildcard asset inclusion is problematic because some assets might depend on being included in other asset files and not compiled directly.  The twitter bootstrap-sass gem, used indirectly by a fork of calagator (ActivateHub), fails with wildcard matching:
http://stackoverflow.com/questions/9915950/bootstrap-sass-undefined-variable-baselineheight
#### Possible Solutions

_(my preference is 4 but I want to run it by others first)_
1. Do nothing.  Let theme developers use command-line tools like `lessc` to compile assets.
2. Move theme assets to app/assets/{images,javascripts,stylesheets}/:theme_name directories.  Reference assets using `stylesheet_link_tag(':theme_name/foo.css')` instead of `theme_stylesheet_link_tag('foo.css')`.  Views can stay in themes/ but they will be lonely.
3. Try one of the forks.  Have everyone move their assets from directories like `themes/*/javascripts` to `themes/*/assets/javascripts`.  Standardize on which assets will be precompiled by default (i.e. ":theme/*/theme.{css,js}) and/or add an additional configuration in the theme settings file that adds to the `config.assets.precompile` array.
4. Move away from themes_for_rails as it adds unneeded complexity to the application.  Similar theme behaviour can be accomplished using something like:
   
   ``` ruby
   # config/application.rb
   THEME_NAME = "default" # name loaded using ThemeReader module
   theme_asset_glob = Rails.root.join('themes', THEME_NAME, '{javascripts,stylesheets,images}')
   config.assets.paths.prepend(*Dir[theme_asset_glob])
   config.assets.precompile += SETTINGS.precompile_assets || [] # precompile_assets: %w( nyan_cat.js ) in theme settings file
   
   # app/controllers/application_controller.rb
   before_filter :set_theme
   def set_theme
       prepend_view_path "themes/#{THEME_NAME}/views"
   end
   ```
   
   One of the advantages with this approach is that it still allows themes to override view files, but also allows a theme to override a core calagator asset (i.e. an image defined in app/assets/images), just by creating another file with the same name.  Forks with custom themes wouldn't have to move files around but they would have to modify their views to stop using the `theme_` prefix for helpers such as `theme_stylesheet_link_tag`.  This transition could be made easier by aliasing the helper methods back to non-theme variants.  I believe they can also include the original file by doing something like (I haven't tried it, but conceptually possible):
   
   ``` css
   /* # themes/foo/stylesheets/application.css (or .scss or .less)
   *= require ../../../app/assets/stylesheets/application.css
   *= require_self
   */
   body { text-decoration: blink; }
   
   .5. Other suggestions???
   
   
   #### IE6 / IE7 Support
   In my fork's asset_pipeline branch, I removed the ie.css and formtastic_ie?.css files as there isn't really a good way to test support for those browsers anymore and their usage is likely very low.  It's easy to revert that commit, but I propose to officially remove support for IE6/7 when moving to the asset pipeline, keeping ie.css out of the config.assets.precompile list.
   
   There are CSS hacks that are meant to only trigger stylesheet changes in IE6/7 that cause asset precompilation to fail when passed through a CSS uglifier; to fix those also requires removing those hacks.
   
   For example, the following error is triggered by an asterisk prefixing the _html_ element in the datepicker.css stylesheet:
   ```

```
$> bundle exec rake assets:precompile
rake aborted!
Invalid CSS after "*": expected "{", was "html .datepicke..."

"html" may only be used at the beginning of a compound selector.
  (in /home/daniel/Programming/calagator/app/assets/stylesheets/forms.css)(sass):44
/home/daniel/Programming/calagator/vendor/bundle/gems/sass-3.2.9/lib/sass/scss/parser.rb:1148:in `expected'
/home/daniel/Programming/calagator/vendor/bundle/gems/sass-3.2.9/lib/sass/scss/parser.rb:1084:in `expected'
```

``` css
/* app/assets/stylesheets/datepicker.css:44-46 */
*html .datepicker_prompt {
  width: 185px;
}
```

Also see: http://stackoverflow.com/questions/645865/what-is-the-scope-of-the-css-hack
